---
- name: Deploy Spring Boot application from S3 to EC2
  hosts: all
  become: yes
  vars:
    app_name: spring-boot-app
    s3_bucket: swin-c6g1-report-bucket
    s3_object_key: build/app-v1.0.0.jar
    jar_file: app.jar
    app_install_dir: /opt/onboarding-system
    app_service_name: onboarding-system
    java_package: java-17-amazon-corretto

  tasks:
    - name: Install Java 17 (Amazon Corretto)
      ansible.builtin.yum:
        name: "{{ java_package }}"
        state: present

    - name: Create application directory
      ansible.builtin.file:
        path: "{{ app_install_dir }}"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Empty the application directory
      ansible.builtin.command:
        cmd: "rm -rf {{ app_install_dir }}/*"

    - name: Download JAR from S3 bucket
      ansible.builtin.command:
        cmd: "aws s3 cp s3://{{ s3_bucket }}/{{ s3_object_key }} {{ app_install_dir }}/{{ jar_file }}"

    - name: Create systemd service file for Spring Boot application
      ansible.builtin.copy:
        dest: /etc/systemd/system/{{ app_service_name }}.service
        content: |
          [Unit]
          Description=Spring Boot Application - {{ app_name }}
          After=network.target
          
          [Service]
          User=root
          Environment=TARGET=dev
          ExecStart=/usr/bin/java -jar {{ app_install_dir }}/{{ jar_file }}
          SuccessExitStatus=143
          Restart=on-failure
          RestartSec=5
          
          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to apply changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start Spring Boot service
      ansible.builtin.systemd:
        name: "{{ app_service_name }}"
        state: started
        enabled: yes

    - name: Restart Spring Boot service if it exists
      ansible.builtin.systemd:
        name: "{{ app_service_name }}"
        state: restarted